typography_spectrum: 0.16281
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.7119078820105642
  lightness: 0.5625
  saturation: 0.6245029726997018
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.2705523076001555
analytics:
  google: null
  facebook: null
  twitter: null
name: Simon Goff - Musician
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: ''
purpose: []
